### Probar el endpoint de login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "estefanoquiriconi@gmail.com",
  "password": "123456"
}

### Probar el endpoint de signIn
POST http://localhost:8080/api/auth/signIn
Content-Type: application/json

{
  "email": "estefano@gmail.com",
  "password": "123",
  "firstName" : "Estéfano",
  "lastName": "Quiriconi"
}

### Probar el endpoint protegido con token
GET http://localhost:8080/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJlc3RlZmFub3F1aXJpY29uaUBnbWFpbC5jb20iLCJpYXQiOjE3MjgzODkxNzcsImV4cCI6MTcyODM5Mjc3N30.EtGhxVfAG1d2p7M1iBqH7JLY3pwUEa2qMlbXU_TFZO4
